# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RhEjyTOruv8MdOqmLKpOPlDfn5xHnUDr
"""

import matplotlib.pyplot as plt

notas = [8, 7, 6, 9, 5]

alunos = ['Aluno 1', 'Aluno 2', 'Aluno 3', 'Aluno 4', 'Aluno 5']

explode = [0.1, 0.1, 0.1, 0.1, 0.1]

plt.figure(figsize=(8, 8))
plt.pie(notas, explode=explode, labels=alunos, autopct='%1.1f%%', startangle=90)
plt.title('Notas dos Alunos')
plt.axis('equal')
plt.show()

import matplotlib.pyplot as plt

estacoes = ['Primavera', 'Verão', 'Outono', 'Inverno']

duracao = [3, 3, 3, 3]

plt.bar(estacoes, duracao)
plt.xlabel('Estações do Ano')
plt.ylabel('Duração (meses)')
plt.title('Duração das Estações do Ano')
plt.show()

import matplotlib.pyplot as plt

estacoes = ['Primavera', 'Verão', 'Outono', 'Inverno']

duracao = [3, 3, 3, 3]

temperaturas = [20, 30, 25, 10]

fig, ax1 = plt.subplots()
ax2 = ax1.twinx()
ax1.bar(estacoes, duracao, color='lightblue')
ax2.plot(estacoes, temperaturas, color='orange', marker='o')
ax1.set_xlabel('Estações do Ano')
ax1.set_ylabel('Duração (meses)')
ax2.set_ylabel('Temperatura Média (°C)')
ax1.set_title('Duração e Temperatura das estações do Ano')
plt.show()