# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZ3D_wlfEjKCpFFRiuZtHtuzQ8_eBNVQ
"""

#Atividade 4

#Questão 1

A = float(input("Digite um valor: "))
B = float(input("Digite um valor: "))
C = float(input("Digite um valor: "))



if (A + B < C):
  print(f'Menor')
else:
  print(f'Não é menor')

#Questão 2

num = float(input('Digite um número qualquer: '))

if num % 2 == 0:
  print(f'O número é par')

else:
  print(f'O número é impar')

#Questão 3

numA = float(input('Digite um número: '))
numB = float(input('Digite um número: '))

if numA == numB:
  C = numA + numB
else:
  C = numA * numB

print(f'O resultado é: {C}')

#Questão 4

v1 = bool(input('Digite o primeiro valor booleano (True/False)'))
v2 = bool(input('Digite o primeiro valor booleano (True/False)'))

if v1 and v2:
  print(f"Ambos são verdadeiros")
else:
  print(f'Pelo menos 1 é falso')

#Questão 5

a = int(input('Digite um valor: '))
b = int(input('Digite um valor: '))
c = int(input('Digite um valor: '))

if a > b and a > c:
  maior = a
elif b > a and b > c:
  maior = b
else:
  maior = c


if a < b and a < c:
  menor = a
elif b < a and b < c:
  menor = b
else:
  menor = c

if a != maior and a != menor:
  meio = a
elif b != maior and c != menor:
  meio = b
else:
  meio = c
print(maior, meio, menor)

