# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OZnfUKFNyjEyQ7CuiXy3fnivG47YNdK-
"""

#Atividade 1

estacao_favorita = input("Digite qual sua estação favorita?: ")

if estacao_favorita.lower() == "inverno":
  print("O Inverno é minha estação favorita")
else:
  print("Não gosto dessa estação.")

#Atividade 2

string = input("Digite uma string.")

if string.isupper():
  print("A string contém apenas letras maiúsculas.")
else:
  print("A string contém letras minusculas ou caracteres especiais.")

#Atividade 3

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [3, 4, 5, 6, 7]

plt.plot(x,y)

plt.xlabel('Eixo X')
plt.ylabel('Eixo Y')

plt.title('Gráfico de linha')

plt.show()

#Atividade 4

import matplotlib.pyplot as plt

vendas = [50, 20, 10, 30, 40]
categorias = ['Claudio', 'Gabriel', 'Marcelo', 'Leo', 'Baiuda']

plt.pie(vendas, labels=categorias)

plt.title('Gráfico de pizza de vendas por categoria')

plt.show()

#Atividade 5

import sys

numero = int(input("Digite um número de 0 a 5: "))
if numero > 5:
      sys.exit()
elif numero < 0:
      sys.exit()
else:
      if numero == 5:
        print("Olá!")
      elif numero == 4:
        print("Oi!")
      elif numero == 3:
        print("Como vai?")
      elif numero == 2:
        print("Tudo bem?")
      elif numero == 1:
        print("Que bom!")
      elif numero == 0:
        print("Tchau!")