# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19CeQixaHT2w0_rv9RXBQp4VNFi_ZP9Px
"""

#Atividade 1
a = float (input("Primeiro número: "))
b = float(input("Segundo número: "))
c = float(input("Terceiro número: "))
d = float(input("Quarto número: "))

soma = a + b + c + d
print(f"A soma dos quatro numeros é :{soma}")



#Atividade 2
num1 = float(input('Primeiro número:'))
num2 = float(input('Segundo número:'))
num3 = float(input('Terceiro número:'))
num4 = float(input('Quarto número:'))
num5 = float(input('Quinto número:'))
num6 = float(input('Sexto númeor:'))

media = (num1 + num2 + num3 + num4 + num5 + num6)/6

print(f'A média dos números é:{media}')

#Atividade 3
a = float (input("Primeiro número: "))
b = float(input("Segundo número: "))
c = float(input("Terceiro número: "))
d = float(input("Quarto número: "))

soma = a + b + c + d
print(f"A soma dos quatro numeros é :{soma}")

quadrado = soma * soma
print(f'O quadrado dos números é: {quadrado}')

#Atividade 4
preco = float(input("Qual o preço do produto selecionado?: "))
desconto = preco * 0.05
valorFinal = preco - desconto
print(f"O preço final com desconto é de: {valorFinal}")

#Atividade 5
base = float(input("Qual a base do quadrado?: "))
altura = float(input("Qual a altura do quadrado?: "))

area = base * altura

print(f"A area do quadrado é: {area}")

dobroArea = area * 2

print(f"O dobro da area é: {dobroArea}")

#Atividade 6
ganhoHora = float(input("Quanto o funcionário ganha por hora?: "))
horasT = float(input("Quantas horas o funcionário trabalha por mês?: "))

salario = ganhoHora * horasT

print(f"O salário do funcionário por mês é: {salario}R$")

#Ativdade 7 
lamp = 60
horas = 12
dias = 30

kwh = (lamp*horas)/1000

print(f"O consumo mensal é de: {kwh}kWh")