# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BIgNLb3ZtuLC1FomQBwU1EmhfP751cHJ
"""

#Atividade 1
base = float(input('Digite o comprimento da base do terreno: '))
altura = float(input('Digite a altura do terreno: '))

area = base * altura

print(f'A área do terreno é: {area}')

#Atividade 2

#Atividade 1
base = float(input('Digite o comprimento da base do terreno: '))
altura = float(input('Digite a altura do terreno: '))

area = base * altura

print(f'A área do terreno é: {area}')

area_por_quatro = area / 4

print(f'O lote divido em 4 fica em: {area_por_quatro}')

#Atividade 3

cavalos = 234

quantidade_de_ferradura = cavalos * 4

print(f'A qunatidade de ferradura para os cavalos são de: {quantidade_de_ferradura} ')

#Atividade 4

animais = 129

ferradura = animais * 4

print(f'A quantidade de ferradura é de: {ferradura}')

#Atividade 5

salario_inicial = float(input('Digite o salário inicial: '))
aumento = salario_inicial * 0.15
salario_aumentado = aumento + salario_inicial

print(f'O resultado do salario com aumento é de: {salario_aumentado}')

#Atividade 6

salario_inicial = float(input('Digite o salário inicial: '))
aumento = salario_inicial * 0.27
salario_aumentado = aumento + salario_inicial

print(f'O resultado do salario com aumento é de: {salario_aumentado}')

desconto = salario_aumentado * 0.10
salario_descontado = salario_aumentado - desconto

print(f'Com os impostos fica em: {salario_descontado}')

#Atividade 7

valorIni = float(input('Digite o valor inicial do deposito: '))
poupanca = (valorIni*0.05)
print(f'O valor depois de um mês rendendo apos um mes: {poupanca}')

poupancaAno2 = poupanca * 120
resultado = poupancaAno2 + valorIni

print(f'O valor apos 2  anos rendendo 5% é de: {resultado}')

azul = 2.3333
azul=round(azul,2)
azul

#Atividade 8

combustao = 4.87
odometro = float(input("Quantos KM foram rodados no inicio do dia: "))
odometroFin = float(input("Quantos KM foram rodados no fim do dia: "))
combustaoLitro = float(input('Quantos litros de gasolina foram gastos no dia: '))
valorTotal = float(input('Quanto foi o valor total recebido: '))

km_litro = (odometroFin - odometro)/combustaoLitro

lucro = valorTotal - (combustaoLitro * combustao)

print(f'Media de consumo: {km_litro}KM/L')
print(f'Lucro liquido R${lucro}')

#Atividade 9

gasolina = 4.70
dinheiro = float(input("Digite o valor do abastecimento: "))

total = dinheiro / gasolina
print(f'A quantidade de litros é de: {total}L')