# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ndoo1RlmpxjhvVN-O-S3S3MYQs9OGJ5S
"""

import matplotlib.pyplot as plt

disciplinas = ['DesWeb','Portugues','Matematica','Python','Historia']
media = ['Média']
notas = [3.0 , 2.2 , 3.0 , 4.0 , 6.0 ]
media = [n]
figura = plt.figure(figsize=(30,4))
figura.add_subplot(131)
# pontilhado k--
plt.suptitle('notas alunos! Funec Riacho.')
plt.plot(disciplinas, notas)
plt.plot(disciplinas, notas)
figura.add_subplot(131)
plt.bar(disciplinas, notas)
plt.show()

valor1 = float(input("Digite o valor 1: "))
valor2 = float(input("Digite o valor 2: "))
valor3 = float(input("Digite o valor 3: "))

media = (valor1 + valor2 + valor3)/3

if (media < 6):
  print(f"A média está abaixo de 6.")
elif (media > 6):
    print(f"A média está acima de 6.")
else: 
  print(f"A média está igual a 6")