# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pPzv0gfhrjrZozthBUEJGoFh9KNbARMT
"""

#Atividade 3

#Questão 1

preco = float(input('Digite o preço do produto: '))
desconto = float(input('Digite o desconto: '))
desconto = desconto /100
desconto = desconto*preco
precop = preco - desconto
print(f"O preço com desconto é: {precop}%")

#Questão 2

valor = int(input('Digite um número: '))

adicao = valor +1

print(f'{adicao}')

#Questão 3

valor1 = float(input('Digite um número: '))
valor2 = float(input('Digite um número: '))
valor3 = float(input('Digite um número: '))
valor4 = float(input('Digite um número: '))

soma = valor1 + valor2 + valor3 + valor4
media = soma /4

print(f'A soma é: {soma}, e a media é: {media}')

#Questão 4

alimentoKG = float(input('Quantos kilos de alimento foi recebido?: '))

consumo = (alimentoKG*1000)/50

print(f'O alimento ira durar: {consumo} dias.')

#Questão 5

inteiro = int(input('Digite o valor: '))

resto = inteiro /3

quociente = resto / 3

print(f'O resto é: {resto}')
print(f'O quociente é: {quociente}')

#Questão 6

alimentoKG = float(input('Quantos kilos de alimento foi recebido?: '))

dias = (alimentoKG*100)/120

print(f'O alimento ira durar: {dias} dias.')

#Questão 7


combustao = 2.50
odometro = float(input("Quantos KM foram rodados no inicio do dia: "))
odometroFin = float(input("Quantos KM foram rodados no fim do dia: "))
combustaoLitro = float(input('Quantos litros de gasolina foram gastos no dia: '))
valorTotal = float(input('Quanto foi o valor total recebido: '))

km_litro = (odometroFin - odometro)/combustaoLitro

lucro = valorTotal - (combustaoLitro * combustao)

print(f'Media de consumo: {km_litro}KM/L')
print(f'Lucro liquido R${lucro}')

#Questão 8


valor1 = float(input('Digite um número: '))
valor2 = float(input('Digite um número: '))
valor3 = float(input('Digite um número: '))
valor4 = float(input('Digite um número: '))

soma = valor1 + valor2 + valor3 + valor4
media = soma /4

print(f'A media é: {media}')